spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/t1f/fz.git
          username:
          password:
          default-label: master
  application:
    name: config-client-dev
  profiles:
    active: dev