server:
  port: 8085
#  tomcat:

eureka:
  instance:
    hostman: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8084/eureka/


spring:
  application:
    name: cloudprover

