#tomcat
server:
  port: 8083


eureka:
  instance:
    hostman: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8084/eureka/

#数据库链接信息
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testBygo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: mysql
    redis:
      host:
      password:
      timeout: 2000 #链接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 600 #链接池最大链接数（使用负值表示没有限制）
          max-wait: 1000 #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 300 #连接池中的最大空闲链接
          min-idle: 0 #线程池中的最小空闲链接
          port: 6379
swagger:
  enable: true




